sudo: required
language: python
services:
- docker

script:
- docker image build -t sakman/cps847 .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sakman/cps847